#dictionary 
#Used chatgpt to create dictionary
loteria_dict = {
    "El Gallo": "The Rooster",
    "El Diablo": "The Devil",
    "La Dama": "The Lady",
    "El Catrín": "The Cactus",
    "El Paraguas": "The Umbrella",
    "La Sirena": "The Mermaid",
    "La Escalera": "The Ladder",
    "La Botella": "The Bottle",
    "El Barril": "The Barrel",
    "El Árbol": "The Tree",
    "El Melón": "The Watermelon",
    "El Valiente": "The Valiente",
    "El Gorila": "The Gorilla",  # Replacement for El Negrito
    "El Corazón": "The Heart",
    "La Campana": "The Bell",
    "El Agua": "The Water",
    "La Bota": "The Boot",
    "La Luna": "The Moon",
    "El Perico": "The Parrot",
    "La Mano": "The Hand",
    "La Bandera": "The Flag",
    "El Bandolón": "The Bandit",
    "El Músico": "The Musician",
    "El Sol": "The Sun",
    "El Gorrito": "The Hat",
    "La Muerte": "The Death",
    "La Pera": "The Pear",
    "La Palma": "The Palm Tree",
    "El Pescado": "The Fish",
    "La Estrella": "The Star",
    "El Burro": "The Donkey",
    "La Araña": "The Spider",
    "El Borracho": "The Drunkard",
    "El Violín": "The Violin",
    "La Chalupa": "The Canoe",
    "El Mundo": "The World",
    "El Apache": "The Apache",  # Caution: may be considered outdated
    "La Flecha": "The Arrow",
    "La Corona": "The Crown",
    "El Alacrán": "The Scorpion",
    "La Rosa": "The Rose",
    "La Calavera": "The Skull",
    "La Sandía": "The Bellows",
    "El Camarón": "The Shrimp",
    "El Payaso": "The Jester",  # Creative addition
    "La Rana": "The Frog",
    "La Maceta": "The Flower Pot",
    "El Arpa": "The Harp",
    "El Gallopeine": "The Rooster Comb",  # Fun, non-traditional card
    "La Piña": "The Pineapple"
}
